filebeat.prospectors:

- type: log
  enabled: true
  paths:
    - /root/logs/nginx-online/*.log
    - /root/logs/nginx-prod/*.log
  fields:
    flag: nginx
    mode: syslog
- type: log
  enabled: true
  paths:
    - /root/logs/filebeat/*.log
  fields:
    flag: filebeat
    mode: syslog
output.kafka:
  hosts: ["10.33.80.240:9092"]
  topic: 'log'
  partition.round_robin:
    reachable_only: false
  required_acks: 1
  compression: gzip
  max_message_bytes: 1000000
logging.level: info
