version: '3.3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/real2/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - /var/lib/real2/mysql/initdb:/docker-entrypoint-initdb.d
      - /var/lib/real2/mysql/data:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    restart: always
  redis:
    image: docker.io/redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    command: redis-server
  zookeeper:
    image: zookeeper
    container_name: zookeeper
    restart: always
    ports:
      - "2181:2181"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - zk-data:/data
    environment:
      - TZ=Asia/Shanghai
      - ZOO_MAX_CLIENT_CNXNS=600
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 10.0.8.189
      KAFKA_ZOOKEEPER_CONNECT: 10.0.8.189:2181/kafka
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS: 1000000
      TZ: Asia/Shanghai
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      - kafka-data:/kafka/
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    user: root
    environment:
      - NGINX_PORT=80
    restart: always
    volumes:
      - /var/lib/real2/nginx/reverse-proxy.conf:/etc/nginx/conf.d/default.conf
      - /var/lib/real2/nginx/nginx.conf:/etc/nginx/nginx.conf
      - nginxlog:/var/log/nginx
    command: /bin/bash -c "nginx -g 'daemon off;'"
  filebeat:
    image: registry.cn-beijing.aliyuncs.com/yangzhenwei/filebeat:6.1.0
    container_name: filebeat
    hostname: real
    volumes:
      - /root/logs:/usr/share/filebeat/logs
      - /var/lib/real2/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml

volumes:
  nginxlog:
  kafka-data:
  zk-data:
