version: '3.3'

volumes:
  esdata:
networks:
  esnet:
    external: true
configs:
  ca_crt:
    file: ./certs/ca/ca.crt
  es01_crt:
    file: ./certs/es01/es01.crt
  es01_key:
    file: ./certs/es01/es01.key
  elastic_config:
    file: ./elasticsearch/elasticsearch.yml
  es_proxy_config:
    file: ./es_proxy/nginx.conf
services:
  es01:
    image: reg.zhongjiaxin.com/library/elasticsearch:6.1.0
    environment:
#      ELASTIC_HOST_COMMAND: "docker info | grep 'Node Address:'| cut -d' ' -f 4"
      ELASTIC_NODE_NAME_COMMAND: "docker info | grep ^Name: | cut -d' ' -f 2"
      ES_JAVA_OPTS: -Xms10g -Xmx10g
      ELASTIC_PASSWORD: zhongjiaxin.2017
      TZ: Asia/Shanghai
    ulimits:
      memlock: -1
      nofile:
        hard: 65536
        soft: 65536
      nproc: 65538
    networks:
      - esnet
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /usr/bin/docker:/usr/bin/docker
      - /usr/lib64/libltdl.so.7:/usr/lib64/libltdl.so.7:ro
      - /etc/security/limits.conf:/etc/security/limits.conf
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.elasticsearch == elasticsearch
      resources:
        limits:
          memory: 20g
      update_config:
        parallelism: 1
        delay: 60s
      endpoint_mode: dnsrr
    configs:
      - source: ca_crt
        target: /usr/share/elasticsearch/config/x-pack/certificates/ca/ca.crt
        uid: '1000'
        gid: '0'
        mode: 0440
      - source: es01_crt
        target: /usr/share/elasticsearch/config/x-pack/certificates/elasticsearch/server.crt
        uid: '1000'
        gid: '0'
        mode: 0440
      - source: es01_key
        target: /usr/share/elasticsearch/config/x-pack/certificates/elasticsearch/server.key
        uid: '1000'
        gid: '0'
        mode: 0440
      - source: elastic_config
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        uid: '1000'
        gid: '0'
    ports:
       - target: 9200
         published: 9400
         protocol: tcp
         mode: host
       - target: 9300
         published: 9300
         protocol: tcp
         mode: host
  esproxy:
    image: nginx:latest
    ports:
      - "9200:80"
    networks:
      - esnet
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: 1024M
      update_config:
        parallelism: 1
        delay: 5s
      placement:
        constraints:
          - node.role != manager
      restart_policy:
        condition: on-failure
    configs:
      - source: es_proxy_config
        target: /etc/nginx/nginx.conf
