version: '3.3'

configs:
  filebeat-conf:
    file: ./filebeat/filebeat.yml
networks:
  esnet:
    external: true
volumes:
  filebeatData:
    driver: local
services:
  filebeat-elk:
    image: registry.cn-beijing.aliyuncs.com/yangzhenwei/filebeat:6.1.0
    hostname: log
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
      placement:
        constraints:
          - node.hostname == log
    volumes:
      - /root/logs:/root/logs
      - filebeatData:/usr/share/filebeat/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: Asia/Shanghai
    networks:
      - esnet
    configs:
      - source: filebeat-conf
        target: /usr/share/filebeat/filebeat.yml
