version: '3.3'

networks:
  esnet:
    external: true
services:
  kafka-log:
    image: reg.zhongjiaxin.com/library/kafka-log:master-latest
    hostname: kafka-log
    environment:
      JAVA_OPTS: -Xms1g -Xmx1g
      SPRING_PROFILES_ACTIVE: prod
      TZ: Asia/Shanghai
    volumes:
      - /etc/localtime:/etc/localtime:ro
    deploy:
      mode: replicated
      replicas: 5
      resources:
        limits:
          cpus: '0.7'
          memory: 3072M
      placement:
        constraints:
          - node.labels.kafka == kafka
      restart_policy:
        condition: on-failure
        delay: 5s
      update_config:
        parallelism: 1
        delay: 10s
    networks:
      - esnet
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://10.0.8.122:514"
        tag: "kafka-log"
