version: '3.3'

networks:
  esnet:
    external: true
configs:
  logstash-conf:
    file: ./logstash/logstash.conf
  ca_crt:
    file: ./certs/ca/ca.crt
services:
  logstash02:
    image: registry.cn-beijing.aliyuncs.com/yangzhenwei/logstash:6.1.0
    environment:
      - "xpack.monitoring.elasticsearch.url=https://es01:9200"
      - "xpack.monitoring.elasticsearch.username=elastic"
      - "xpack.monitoring.elasticsearch.password=zhongjiaxin.2017"
      - "xpack.monitoring.elasticsearch.ssl.ca=/usr/share/logstash/certs/ca/ca.crt"
      - "LS_JAVA_OPTS=-Xmx1g"
      - TZ=Asia/Shanghai
    volumes:
      - /etc/localtime:/etc/localtime:ro
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2048M
      mode: replicated
      replicas: 3
      restart_policy:
        condition: on-failure
    ports:
      - "5044:5044"
    networks:
      - esnet
    configs:
      - source: logstash-conf
        target: /usr/share/logstash/pipeline/logstash.conf
      - source: ca_crt
        target: /usr/share/logstash/certs/ca/ca.crt