version: '3.3'

networks:
  esnet:
    external: true
configs:
  logstash-syslog-conf:
    file: ./logstash/logstash_syslog.conf
services:
  logstash01:
    image: registry.cn-beijing.aliyuncs.com/yangzhenwei/logstash:6.1.0
    environment:
      - "LS_JAVA_OPTS=-Xmx2g"
      - "xpack.monitoring.elasticsearch.url=https://es01:9200"
      - "xpack.monitoring.elasticsearch.username=elastic"
      - "xpack.monitoring.elasticsearch.password=zhongjiaxin.2017"
      - "xpack.monitoring.elasticsearch.ssl.ca=/usr/share/logstash/certs/ca/ca.crt"
      - TZ=Asia/Shanghai
    volumes:
      - /etc/localtime:/etc/localtime:ro
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4048M
      mode: replicated
      placement:
        constraints:
          - node.hostname == log
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - target: 514
        published: 514
        protocol: tcp
        mode: host
      - target: 514
        published: 514
        protocol: udp
        mode: host
    volumes:
      - /root/logs:/root/logs
    networks:
      - esnet
    configs:
      - source: logstash-syslog-conf
        target: /usr/share/logstash/pipeline/logstash.conf



#docker run   --name "syslog"  \
#-d  -e LS_JAVA_OPTS="-Xms2g -Xmx2g" \
#--network "esnet" \
#--restart=always   \
#-v /root/logs:/root/logs  \
#-v  /root/logstash/logstash_syslog.conf:/usr/share/logstash/pipeline/logstash.conf  \
#-p "514:514"  -p "514:514/udp" registry.cn-beijing.aliyuncs.com/yangzhenwei/logstash:6.1.0



