version: '2.2'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/real/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - /var/lib/real/mysql/initdb:/docker-entrypoint-initdb.d
      - /var/lib/real/mysql/data:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    restart: always
  redis:
    image: docker.io/redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    command: redis-server
  zookeeper:
    image: zookeeper
    container_name: zookeeper
    restart: always
#    ports:
#      - "2181:2181"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - zk-data:/zk
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Asia/Shanghai
      - ZOO_MAX_CLIENT_CNXNS=600
    network_mode: host
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    restart: always
#    ports:
#      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 10.0.8.199
      KAFKA_LISTENERS: PLAINTEXT://10.0.8.199:9092
      KAFKA_ZOOKEEPER_CONNECT: 10.0.8.199:2181/kafka
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS: 1000000
      TZ: Asia/Shanghai
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - kafka-data:/kafka/
      - /etc/localtime:/etc/localtime:ro
#  dubbo-admin:
#    image: changwentao/dubboadmin:latest
#    container_name: dubbo-admin
#    restart: always
#    ports:
#      - "9050:8080"
#    links:
#      - zookeeper:zookeeper
#    depends_on:
#      - zookeeper
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    user: root
    environment:
      - NGINX_PORT=80
    volumes:
      - /var/lib/real/nginx/reverse-proxy.conf:/etc/nginx/conf.d/default.conf
      - /var/lib/real/nginx/nginx.conf:/etc/nginx/nginx.conf
      - nginxlog:/var/log/nginx
    command: /bin/bash -c "nginx -g 'daemon off;'"
    restart: always
volumes:
  nginxlog:
  kafka-data:
  zk-data:
