version: '3.3'

volumes:
  kafkaData:
    driver: local
networks:
  mynet:
    external: true
services:
  kafka1:
    image: wurstmeister/kafka
    deploy:
      mode: global
      endpoint_mode: dnsrr
      restart_policy:
        condition: on-failure
        delay: 5s
      placement:
        constraints:
          - node.hostname == db-cluster1
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 10.0.8.117
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      KAFKA_MESSAGE_MAX_BYTES: 3000000
      TZ: Asia/Shanghai
    networks:
      mynet:
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://10.0.8.122:514"
        tag: "kafka"
    ports:
      - target: 9092
        published: 9092
        protocol: tcp
        mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - kafkaData:/kafka
  kafka2:
    image: wurstmeister/kafka
    deploy:
      mode: global
      endpoint_mode: dnsrr
      restart_policy:
        condition: on-failure
        delay: 5s
      placement:
        constraints:
          - node.hostname ==  db-cluster2
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 10.0.8.116
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      KAFKA_MESSAGE_MAX_BYTES: 3000000
      TZ: Asia/Shanghai
    networks:
      mynet:
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://10.0.8.122:514"
        tag: "kafka"
    ports:
      - target: 9092
        published: 9092
        protocol: tcp
        mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - kafkaData:/kafka
  kafka3:
    image: wurstmeister/kafka
    deploy:
      mode: global
      endpoint_mode: dnsrr
      restart_policy:
        condition: on-failure
        delay: 5s
      placement:
        constraints:
          - node.hostname == db-cluster3
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 10.0.8.115
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      KAFKA_MESSAGE_MAX_BYTES: 3000000
      TZ: Asia/Shanghai
    networks:
      mynet:
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://10.0.8.122:514"
        tag: "kafka"
    ports:
      - target: 9092
        published: 9092
        protocol: tcp
        mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - kafkaData:/kafka
  kafka-manager:
    image: sheepkiller/kafka-manager
    hostname: kafka-manager
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
      placement:
        constraints:
          - node.hostname == db-cluster1
    environment:
      ZK_HOSTS: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      TZ: Asia/Shanghai
    networks:
      mynet:
    ports:
      - "9000:9000"


