version: '2.2'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/test4/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - /var/lib/test4/mysql/initdb:/docker-entrypoint-initdb.d
      - /var/lib/test4/mysql/data:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    restart: always
  redis:
    image: docker.io/redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    command: redis-server
  zookeeper:
    image: zookeeper
    container_name: zookeeper
    restart: always
#    ports:
#      - "2181:2181"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - zk-data:/zk
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Asia/Shanghai
      - ZOO_MAX_CLIENT_CNXNS=600
    network_mode: host
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    restart: always
#    ports:
#      - "9092:9092"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://10.33.80.108:9092
      KAFKA_ZOOKEEPER_CONNECT: 10.33.80.108:2181/kafka
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS: 1000000
      TZ: Asia/Shanghai
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - kafka-data:/kafka/
      - /etc/localtime:/etc/localtime:ro
volumes:
  kafka-data:
  zk-data:


