version: '2.2'

services:
  mysql:
    image: mysql:5.6
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/jenkins_dev/alert/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - /var/lib/jenkins_dev/alert/mysql/initdb:/docker-entrypoint-initdb.d
      - /var/lib/jenkins_dev/alert/mysql/data:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    restart: always
  redis:
    image: docker.io/redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
    command: redis-server
  kafka-manager:
    image: sheepkiller/kafka-manager
    container_name: kafka-manager
    hostname: kafka-manager
    restart: always
    environment:
      ZK_HOSTS: zookeeper:2181
      TZ: Asia/Shanghai
    ports:
      - "9000:9000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
  zookeeper:
    image: zookeeper
    container_name: zookeeper
    restart: always
    ports:
      - "2181:2181"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - zk-data:/zk
    environment:
      - TZ=Asia/Shanghai
volumes:
  zk-data:

