filebeat.prospectors:

- type: log
  enabled: true
  paths:
    - /usr/share/filebeat/logs/phpmyadmin.log
  fields:
    flag: phpadmin
output.kafka:
  hosts: ["10.0.8.112:9092", "10.0.8.113:9092", "10.0.8.114:9092"]
  topic: 'log'
  partition.round_robin:
    reachable_only: false
  required_acks: 1
  compression: gzip
  max_message_bytes: 1000000
logging.level: info
