version: '3.4'

networks:
  app:
    external: true
services:
  channel-inner-web:
    image: reg.zhongjiaxin.com/library/channel-inner-web:master-latest
    hostname: channel-inner-web
    environment:
      SPRING_PROFILES_ACTIVE: prod
      JAVA_OPTS: >
        -Dserver.port=8010
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: 3072M
      placement:
        constraints:
          - node.labels.prod == prod
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 120s
      update_config:
        parallelism: 1
        failure_action: rollback
        max_failure_ratio: 0
        delay: 10s
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8010/channel/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    ports:
      - target: 8010
        published: 8010
        protocol: tcp
        mode: host
    networks:
       - app
    volumes:
       - /root/logs:/logs
