version: '3.3'

configs:
  nginx-conf:
    file: ./nginx/nginx.conf
services:
  nginx:
    image: nginx:latest
    hostname: nginx
    deploy:
      mode: global
      endpoint_mode: dnsrr
      update_config:
        parallelism: 1
        delay: 5s
      placement:
        constraints:
          - node.labels.prod == prod
      restart_policy:
        condition: on-failure
    configs:
      - source: nginx-conf
        target: /etc/nginx/nginx.conf
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://10.0.8.122:514"
        tag: "nginx-prod"
    volumes:
     - /etc/localtime:/etc/localtime:ro
    environment:
     - TZ=Asia/Shanghai
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
