version: '3.3'

volumes:
  kafkaData:
    driver: local
networks:
  esnet:
    external: true
services:
  kafka1:
    image: wurstmeister/kafka
    deploy:
      mode: global
      endpoint_mode: dnsrr
      restart_policy:
        condition: on-failure
        delay: 5s
      placement:
        constraints:
          - node.hostname == elk1
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 10.33.80.122
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      TZ: Asia/Shanghai
    networks:
      esnet:
#    logging:
#      driver: syslog
#      options:
#        syslog-address: "tcp://10.33.80.122:514"
#        tag: "kafkaELK"
    ports:
      - target: 9092
        published: 9092
        protocol: tcp
        mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - kafkaData:/kafka
  kafka2:
    image: wurstmeister/kafka
    deploy:
      mode: global
      endpoint_mode: dnsrr
      restart_policy:
        condition: on-failure
        delay: 5s
      placement:
        constraints:
          - node.hostname == elk2
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 10.33.80.123
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      TZ: Asia/Shanghai
    networks:
      esnet:
    ports:
      - target: 9092
        published: 9092
        protocol: tcp
        mode: host
#    logging:
#      driver: syslog
#      options:
#        syslog-address: "tcp://10.33.80.122:514"
#        tag: "kafkaELK"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - kafkaData:/kafka
  kafka3:
    image: wurstmeister/kafka
    deploy:
      mode: global
      endpoint_mode: dnsrr
      restart_policy:
        condition: on-failure
        delay: 5s
      placement:
        constraints:
          - node.hostname == elk3
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 10.33.80.124
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      TZ: Asia/Shanghai
    networks:
      esnet:
    ports:
      - target: 9092
        published: 9092
        protocol: tcp
        mode: host
#    logging:
#      driver: syslog
#      options:
#        syslog-address: "tcp://10.33.80.122:514"
#        tag: "kafkaELK"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - kafkaData:/kafka
  kafka-manager:
    image: sheepkiller/kafka-manager
    hostname: kafka-manager
    deploy:
      mode: global
      endpoint_mode: dnsrr
      restart_policy:
        condition: on-failure
        delay: 5s
      placement:
        constraints:
          - node.hostname == elk2
    environment:
      ZK_HOSTS: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
    networks:
      esnet:
    ports:
      - target: 9000
        published: 9000
        protocol: tcp
        mode: host


