version: '3.3'

volumes:
  kafkaData:
    driver: local
  zkdata:
    driver: local
networks:
  mynet:
    external: true
services:
  zoo1:
    image: zookeeper
    restart: always
    hostname: zoo1
    container_name: zookeeper_1
    ports:
      - 2181:2181
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - zkdata:/zk
    environment:
      TZ: Asia/Shanghai
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    networks:
      mynet:
  zoo2:
    image: zookeeper
    restart: always
    hostname: zoo2
    container_name: zookeeper_2
    ports:
      - 2182:2181
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - zkdata:/zk
    environment:
      TZ: Asia/Shanghai
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    networks:
      mynet:
  zoo3:
    image: zookeeper
    restart: always
    hostname: zoo3
    container_name: zookeeper_3
    ports:
      - 2183:2181
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - zkdata:/zk
    environment:
      TZ: Asia/Shanghai
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    networks:
      mynet:
  kafka1:
    image: wurstmeister/kafka
    restart: always
    hostname: kafka1
    container_name: kafka_1
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 10.0.8.128
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://10.0.8.128:9092
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2182,zoo3:2183
      KAFKA_MESSAGE_MAX_BYTES: 3000000
      TZ: Asia/Shanghai
    ports:
      - "9092:9092"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - kafkaData:/kafka
    networks:
      mynet:
  kafka2:
    image: wurstmeister/kafka
    restart: always
    hostname: kakfa2
    container_name: kafka_2
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 10.0.8.128
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://10.0.8.128:9092
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2182,zoo3:2183
      KAFKA_MESSAGE_MAX_BYTES: 3000000
      TZ: Asia/Shanghai
    ports:
      - "9093:9092"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - kafkaData:/kafka
    networks:
      mynet:
  kafka3:
    image: wurstmeister/kafka
    restart: always
    hostname: kafka3
    container_name: kafka_3
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 10.0.8.128
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://10.0.8.128:9092
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2182,zoo3:2183
      KAFKA_MESSAGE_MAX_BYTES: 3000000
      TZ: Asia/Shanghai
    ports:
      - "9094:9092"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - kafkaData:/kafka
    networks:
      mynet:
  kafka-manager:
    image: sheepkiller/kafka-manager
    hostname: kafka-manager
    container_name: kafka_manager
    restart: always
    environment:
      ZK_HOSTS: zoo1:2181,zoo2:2182,zoo3:2183
      TZ: Asia/Shanghai
    ports:
      - "9091:9000"
    networks:
      mynet: